### ISSUE TITLE
PKGBUILD building from source

### ISSUE THREAD

**Issue by yochananmarqos** [mingue/journal-viewer#1]
Feel free to add it to the AUR if you'd like: [`journal-viewer`](https://github.com/yochananmarqos/pkgbuilds/tree/master/journal-viewer)

**Comment by mingue** [comment]
I published it on the AUR already [journal-viewer-bin](https://aur.archlinux.org/packages/journal-viewer-bin) thanks for your suggestions there. 
I'm new publishing packages there so probably missing a few things, like the desktop file as per your repo. I have to work on automating the whole build process as it a bit tedious at the moment

**Comment by yochananmarqos** [comment]
Yes, I was already aware you've added the binary version to the AUR. I've also commented there. :wink:

**Comment by mingue** [comment]
Added src option on AUR and automated most of the release process, except pushing to AUR
