### ISSUE TITLE
Wayland problems

### ISSUE THREAD

**Issue by enzi** [mingue/journal-viewer#21]
Running journal-viewer under Wayland crashes with this error:

journal-viewer
`Gdk-Message: 14:45:39.655: Error 71 (Protocol error) dispatching to Wayland display.`

GDK_BACKEND=x11 journal-viewer
`Failed to create GBM buffer of size 1024x800: Invalid argument`
and ends in a blank grey window

Workaround:
GDK_BACKEND=x11 WEBKIT_DISABLE_DMABUF_RENDERER=1 journal-viewer

Arch Linux/KDE
Nvidia driver: 560.35.03
egl-wayland 4:1.1.16-1

**Comment by mingue** [comment]
Hi @enzi  thanks for reporting the issue. I think this might be an issue on Nvidia drivers. I also run Arch/KDE and don't have these issues.

I don't want to disable DMABUF for everyone as it might have performance implications. I suggest you update your Desktop entry to include the workaround you suggested to avoid having to launch the application from the cmdline
