### ISSUE TITLE
[feature request] Is it possible to provide a `.deb` package that works with older glibc versions?

### ISSUE THREAD

**Issue by m-ueberall** [mingue/journal-viewer#7]
The `.deb` unfortunately doesn't work on Ubuntu 20.04/Focal (and Debian 11/Bullseye uses the same glibc version 2.31):
```
[2023-04-14T11:20:17+0200] ueberall_l@desktop01:~/Videos% journal-viewer
journal-viewer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by journal-viewer)
journal-viewer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by journal-viewer)
journal-viewer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by journal-viewer)
[2023-04-14T11:20:19+0200] ueberall_l@desktop01:~/Videos%  ldd --version | head -1
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

**Comment by mingue** [comment]
More details about the issue can be found here https://github.com/rust-lang/rust/issues/57497

It looks like I just need to build with ubuntu 20.04, so it should be an easy fix reusing the pipelines I already have

**Comment by mingue** [comment]
Published a new version that supports debian 11 and ubuntu 20.04.

Also added a couple more filters and improvements :-)
